#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="blog.bkcoding.com")]
	public partial class MyDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertmfc(mfc instance);
    partial void Updatemfc(mfc instance);
    partial void Deletemfc(mfc instance);
    partial void Insertposts(posts instance);
    partial void Updateposts(posts instance);
    partial void Deleteposts(posts instance);
    #endregion
		
		public MyDBDataContext() : 
				base(global::BK.Models.Properties.Settings.Default.www_bkcoding_comConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<mfc> mfc
		{
			get
			{
				return this.GetTable<mfc>();
			}
		}
		
		public System.Data.Linq.Table<posts> posts
		{
			get
			{
				return this.GetTable<posts>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mfc")]
	public partial class mfc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _otherName;
		
		private string _type;
		
		private int _orderby;
		
		private string _icon;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnotherNameChanging(string value);
    partial void OnotherNameChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnorderbyChanging(int value);
    partial void OnorderbyChanged();
    partial void OniconChanging(string value);
    partial void OniconChanged();
    #endregion
		
		public mfc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string otherName
		{
			get
			{
				return this._otherName;
			}
			set
			{
				if ((this._otherName != value))
				{
					this.OnotherNameChanging(value);
					this.SendPropertyChanging();
					this._otherName = value;
					this.SendPropertyChanged("otherName");
					this.OnotherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderby", DbType="Int NOT NULL")]
		public int orderby
		{
			get
			{
				return this._orderby;
			}
			set
			{
				if ((this._orderby != value))
				{
					this.OnorderbyChanging(value);
					this.SendPropertyChanging();
					this._orderby = value;
					this.SendPropertyChanged("orderby");
					this.OnorderbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icon", DbType="VarChar(20)")]
		public string icon
		{
			get
			{
				return this._icon;
			}
			set
			{
				if ((this._icon != value))
				{
					this.OniconChanging(value);
					this.SendPropertyChanging();
					this._icon = value;
					this.SendPropertyChanged("icon");
					this.OniconChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.posts")]
	public partial class posts : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.DateTime _createTime;
		
		private string _writer;
		
		private bool _isDel;
		
		private string _title;
		
		private string _pic;
		
		private string _excerpt;
		
		private decimal _readcount;
		
		private string _content;
		
		private int _mfcID;
		
		private string _mfcName;
		
		private string _mfcOtherName;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncreateTimeChanging(System.DateTime value);
    partial void OncreateTimeChanged();
    partial void OnwriterChanging(string value);
    partial void OnwriterChanged();
    partial void OnisDelChanging(bool value);
    partial void OnisDelChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnpicChanging(string value);
    partial void OnpicChanged();
    partial void OnexcerptChanging(string value);
    partial void OnexcerptChanged();
    partial void OnreadcountChanging(decimal value);
    partial void OnreadcountChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OnmfcIDChanging(int value);
    partial void OnmfcIDChanged();
    partial void OnmfcNameChanging(string value);
    partial void OnmfcNameChanged();
    partial void OnmfcOtherNameChanging(string value);
    partial void OnmfcOtherNameChanged();
    #endregion
		
		public posts()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createTime", DbType="DateTime NOT NULL")]
		public System.DateTime createTime
		{
			get
			{
				return this._createTime;
			}
			set
			{
				if ((this._createTime != value))
				{
					this.OncreateTimeChanging(value);
					this.SendPropertyChanging();
					this._createTime = value;
					this.SendPropertyChanged("createTime");
					this.OncreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_writer", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string writer
		{
			get
			{
				return this._writer;
			}
			set
			{
				if ((this._writer != value))
				{
					this.OnwriterChanging(value);
					this.SendPropertyChanging();
					this._writer = value;
					this.SendPropertyChanged("writer");
					this.OnwriterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDel", DbType="Bit NOT NULL")]
		public bool isDel
		{
			get
			{
				return this._isDel;
			}
			set
			{
				if ((this._isDel != value))
				{
					this.OnisDelChanging(value);
					this.SendPropertyChanging();
					this._isDel = value;
					this.SendPropertyChanged("isDel");
					this.OnisDelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pic", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string pic
		{
			get
			{
				return this._pic;
			}
			set
			{
				if ((this._pic != value))
				{
					this.OnpicChanging(value);
					this.SendPropertyChanging();
					this._pic = value;
					this.SendPropertyChanged("pic");
					this.OnpicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_excerpt", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string excerpt
		{
			get
			{
				return this._excerpt;
			}
			set
			{
				if ((this._excerpt != value))
				{
					this.OnexcerptChanging(value);
					this.SendPropertyChanging();
					this._excerpt = value;
					this.SendPropertyChanged("excerpt");
					this.OnexcerptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readcount", DbType="Decimal(18,0) NOT NULL")]
		public decimal readcount
		{
			get
			{
				return this._readcount;
			}
			set
			{
				if ((this._readcount != value))
				{
					this.OnreadcountChanging(value);
					this.SendPropertyChanging();
					this._readcount = value;
					this.SendPropertyChanged("readcount");
					this.OnreadcountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mfcID", DbType="Int NOT NULL")]
		public int mfcID
		{
			get
			{
				return this._mfcID;
			}
			set
			{
				if ((this._mfcID != value))
				{
					this.OnmfcIDChanging(value);
					this.SendPropertyChanging();
					this._mfcID = value;
					this.SendPropertyChanged("mfcID");
					this.OnmfcIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mfcName", DbType="NVarChar(50)")]
		public string mfcName
		{
			get
			{
				return this._mfcName;
			}
			set
			{
				if ((this._mfcName != value))
				{
					this.OnmfcNameChanging(value);
					this.SendPropertyChanging();
					this._mfcName = value;
					this.SendPropertyChanged("mfcName");
					this.OnmfcNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mfcOtherName", DbType="NVarChar(50)")]
		public string mfcOtherName
		{
			get
			{
				return this._mfcOtherName;
			}
			set
			{
				if ((this._mfcOtherName != value))
				{
					this.OnmfcOtherNameChanging(value);
					this.SendPropertyChanging();
					this._mfcOtherName = value;
					this.SendPropertyChanged("mfcOtherName");
					this.OnmfcOtherNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
